name: deliveryapp
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# App version
version: 1.0.0+1

# Environment SDK version
environment:
  sdk: ^3.6.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  assets:
    - C:\Samarth Thaker\Flutter Projects\deliveryapp\lib\assets\logo.jpeg
