name: deliveryapp
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# App version
version: 1.0.0+1

# Environment SDK version
environment:
  sdk: ^3.6.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0

# Dependency overrides to fix geolocator_android crash
dependency_overrides:
  geolocator_android: ^4.3.9

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
